import React,{useContext,useState} from 'react'
import Head from 'next/head'
import {firebaseapp} from "./components/firebase"
import {getFirestore} from "firebase/firestore"
import {getAuth} from  "firebase/auth";
import {setDoc,doc} from "firebase/firestore"
import { updateDoc,arrayUnion, onSnapshot } from "firebase/firestore"; 
import { Auth } from './components/Context';

function Createpost() {
const [title,setTitle] = useState('')
const [post,setPost] = useState('')
const projectfirestore = getFirestore(firebaseapp)
const auth = getAuth(firebaseapp)
const {user} = useContext(Auth)

  const posts = async ()=>{
    updateDoc(doc(projectfirestore,"singleUser",`${user?.email}`),{
      saveShows:arrayUnion({
          title:title,
          post:post
      })
    })
    setDoc(
      doc(projectfirestore, "posts",user.uid),{
       title:title,
       post:post,
        id:user.uid
      });
      setPost('')
      setTitle('')
    }
  
  

  return (
  <>
    <Head>
        <title>Create a story </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className='h-[100vh] flex flex-col items-center justify-center gap-[30px]'>
    <div className='flex flex-col gap-[10px]  '>
        <label className="text-1xl font-bold">Title</label>
        <input type="text" placeholder='Give a Title' className='border border-2-gray p-2 w-[600px] focus:outline-[#D1358F]' value={title} onChange={(e)=>setTitle(e.target.value)}/>
    </div>

    <div className='flex flex-col gap-[10px]  '>
        <label className="text-1xl font-bold">Write your story</label>
       <textarea rows="10" cols="60" placeholder="Create a Post"  className='border border-2-gray p-2 w-[600px] focus:outline-[#D1358F]' value={post} onChange={(e)=>setPost(e.target.value)}/>
    </div>
<div>
<button className="bg-[#D1358F] p-2 w-[300px] rounded mt-[15px] text-white" onClick={posts}>Submit</button>
</div>
  </div>
  
  </>
  )
}

export default Createpost