import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from "next/router"
import styles from '../styles/Home.module.css'
import {useState} from "react"
import Navbar from './components/Navbar'
import Footer from "./components/Footer"

export default function Home() {
  const router = useRouter();
  const [open,setOpen] = useState(false)
  return (
    <>
      <Head>
        <title>Community of Writers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <header  className='  '>
        <div className=' md:block hidden'>
        <Image src="/Mask Group.png" width={1400} height={500} alt="bg" ></Image>
       
        </div>
        <div className=' flex justify-between flex-col-reverse md:flex-row' style={{zIndex:2}}>
          <div className='md:ml-[150px] md:-mt-[100px] z-10 px-4'>
            <h1 className="md:text-7xl text-[#71341A] text-6xl ">Tell your <br/>own story</h1>
            <p className='w-[350px] mt-[30px] text-sm'>Community of different writers and readers, you can wite your own story and read other people stories</p>
            <div>
              <button className='text-white bg-[#231A36] p-2 rounded-full w-[170px] mt-[30px]' onClick={()=>router.push("signup")}>Get Started</button>
            </div>
          </div>
          <div className='md:-mt-[350px] mt-[100px]'>
          <Image src="/Group 1000001628.png" width={600} height={600} alt="icon" ></Image>
          </div>
        
        </div>
     

      </header>


      <div className='BigContainer mt-[100px] flex flex-col items-center justify-center'>
        <div>
          <h1 className='text-center text-3xl font-bold mb-[20px]'>Community Of Writers</h1>
          <p className='text-sm md:w-[450px] text-center'>Join thousands of writers and readers on melodax and get educated with different ideas and knowledge </p>
        </div>

        <div className='flex gap-[30px] flex-col md:flex-row px-3'>
          <div className='md:w-[400px] mt-[80px]'>
            <h3 className='text-[#C66DE4] font-bold text-sm mb-[6px]'>CONTENT</h3>
            <h1 className='text-2xl font-bold mb-[10px]'>Content Marketing</h1>
            <p>Create infinite pieces of content with our us and be able to market your content</p>
            <p className='text-[#C66DE4] mt-[30px]'>Get Started</p>

          </div>
          <Image src="/card.png" width={350} height={350}  alt="icon"></Image>

        </div>
        <div className='flex gap-[30px] flex-col-reverse md:flex-row px-3'>

<Image src="/profile.png" width={350} height={350}  alt="icon"></Image>
  <div className='md:w-[400px] mt-[80px]'>
  <h3 className='text-[#FBBA33] font-bold text-sm mb-[6px]'>COMMUNITY</h3>
            <h1 className='text-2xl font-bold mb-[10px]'>Community Marketing</h1>
            <p>Bring your relationships with higher heights with other writers and readers on our platform</p>
            <p className='text-[#FBBA33] mt-[30px] cursor-pointer' onClick={()=>router.push("signup")}>Join Us</p>

  </div>
 

</div>

        <div className='flex gap-[30px] flex-col md:flex-row px-3'>

        <div className='md:w-[400px] mt-[80px]'>
  <h3 className='text-[#C66DE4] font-bold text-sm mb-[6px]'>SERVICES</h3>
            <h1 className='text-2xl font-bold mb-[10px]'>Managed Services</h1>
            <p>Our full services solutions allow writers to put/Store their ideas  or knowledge in one place which they share to other people on/out of the platform </p>
            <p className='text-[#C66DE4] mt-[30px] cursor-pointer' onClick={()=>router.push("login")}>Login</p>

  </div>

        <Image src="/card (1).png" width={350} height={350} alt="icon"></Image>
          
         

        </div>

      </div>

      <div className='bg-[#231A36] h-[350px] flex  justify-center p-4'>
        <div>
          <div>
            <h1 className='text-white md:text-3xl font-bold text-center mt-[50px]'>Search through more than one thousands <br/>authors content</h1>
            <p className='text-white text-center md:w-[550px] text-sm mt-[20px]'>Melodax occupies more than one thousands different stories and knowledge, where you get educated and get more ideas</p>
          </div>
          <div className='flex justify-between items-center gap-[50px] mt-[40px]'>
            <div className="flex flex-col items-center justify-center text-white">
              <h3 className='font-bold text-2xl text-center'>600</h3>
              <p className='text-center'>active users</p>
            </div>

            <div className="flex flex-col items-center justify-center text-white">
              <h3 className='font-bold text-2xl text-center'>1000</h3>
              <p className='text-center'>Satisfied clients</p>
            </div>

            <div className="flex flex-col items-center justify-center text-white">
              <h3 className='font-bold text-2xl'>900+</h3>
              <p className='text-center'>Stories</p>
            </div>
          </div>

        </div>

      </div>


      <div className='mt-[100px] flex-col flex items-center justify-center'>
        <div>
            <h1 className='text-center font-bold tex-4xl'>Our Active Users</h1>
            <p className='text-center text-sm mt-[20px] px-2'>Here are some of our active users on melodax. Join Us!!!</p>
        </div>

        <div className="flex items-center justify-center gap-[50px] mt-[50px] flex-col md:flex-row">
          <div className='relative'>
          <Image src="/image02.png" width={350} height={250} alt="icon"></Image>
          <div className='bg-white shadow w-[200px] h-[100px] absolute bottom-0 md:-left-[30px] flex flex-col px-3 justify-center left-0'>
              <h3 className='font-bold text-sm'>Author</h3>
              <div className='flex gap-[30px]'>
                <div>
                  <h2 className=' text-2xl'>40</h2>
                  <p className='text-sm'>Contents</p>
                </div>
                <div>
                  <h2 className=' text-2xl'>70</h2>
                  <p className='text-sm'>Likes</p>
                </div>
              </div>
          </div>
          </div>

          <div className='relative'>
          <Image src="/image01.png" width={350} height={250} alt="icon"></Image>
          <div className='bg-white shadow w-[200px] h-[100px] absolute bottom-0 md:-left-[30px] flex flex-col px-3 justify-center left-0'>
          <h3 className='font-bold text-sm'>Author</h3>
              <div className='flex gap-[30px]'>
                <div>
                  <h2 className=' text-2xl'>100</h2>
                  <p className='text-sm'>Contents</p>
                </div>
                <div>
                  <h2 className=' text-2xl'>150</h2>
                  <p className='text-sm'>Likes</p>
                </div>
              </div>

          </div>
          </div>
          <div className='relative'>
          <Image src="/image03@2x.png" width={350} height={250} alt="icon"></Image>
          <div className='bg-white shadow w-[200px] h-[100px] absolute bottom-0 md:-left-[30px] flex flex-col px-3 justify-center left-0'>
          <h3 className='font-bold text-sm'>Author</h3>
              <div className='flex gap-[30px]'>
                <div>
                  <h2 className=' text-2xl'>80</h2>
                  <p className='text-sm'>Contents</p>
                </div>
                <div>
                  <h2 className=' text-2xl'>30</h2>
                  <p className='text-sm'>Likes</p>
                </div>
              </div>
          </div>
          </div>
        </div>

      </div>


      <div className='mt-[100px] flex-items-center justify-center'>
        <div>
          <div>
            <h1 className='font-bold text-3xl text-center'>Comments</h1>
            <p className='text-center text-1xl mt-[20px]'>Good accountability and comments from users encourages us to provide more features</p>
          </div>

          <div className='flex mt-[80px] items-center justify-center gap-[150px] flex-col md:flex-row'>
            <div className='md:w-[400px] px-2'>
              <p>
                Not weekly or monthly like other sites out there. This ensures proper writing platform for authors to bleed their intentions and also teach other users on the internet
              </p>
              <div className='mt-[70px]'>
                <h3 className='font-bold'>Roy Smith</h3>
                <p>Author</p>
              </div>
            </div>
          <Image src="/image.png" width={350} height={350} alt="icon"></Image>

          </div>
        </div>

      </div>

      <div className='flex items-center justify-center mt-[80px] text-white'>
        <div className='h-[250px] w-[900px] rounded flex flex-col items-center justify-center' style={{background:'url("/Mask Group.png")'}}>
          <h1 className='text-2xl font-bold mb-[20px]'>Subscribe to our newsletter</h1>
          <p className='text-center'>Join our list and get updates on latest new content fom authors and writers</p>

          <div>
              <button className='text-white bg-[#231A36] p-2 rounded-full w-[170px] mt-[30px]'>Subscribe</button>
            </div>

        </div>
      </div>

    <Footer/>

       
    </>
  )
}
