import React,{useState} from 'react'
import {useRouter} from "next/router"
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import {signInWithEmailAndPassword} from 'firebase/auth';
import {getAuth} from  "firebase/auth";
import {firebaseapp} from "./components/firebase"

function Login() {

  const [error,setError] = useState(null)
    const [email,setEmail] = useState('')
    const [password,setPassword] = useState('')
    const [success,setSuccess] = useState(null)
    const router = useRouter();
    const auth = getAuth(firebaseapp);



    const  login = async (e)=>{
      e.preventDefault();
      //setLoading(true)
  
      if(email === "" || !password === "" ){
        setError("Fields are empty")
        //setLoading(false)
      }
  
     else{
      try{
        await signInWithEmailAndPassword(auth,email,password)
      // setLoading(false)
       router.push("melodax");
       setSuccess("Welcome to Melodax")
       
     }
     catch(err){
       console.log(err)
       setError(err.message)
     }
  
     }
     
     
    
  
    }

  return (

    <>
     <Head>
        <title>Our Login Page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="h-[100vh]  relative flex items-center justify-center md:flex-row flex-col">

      
    <div className="h-[100vh] bg-[#D1358F] text-white w-[700px] md:flex items-center justify-center ">
<h1 className='md:text-5xl font-bold text-center mt-[50px] text-3xl'>WELCOME BACK</h1>
      </div>
           
           <div className="flex items-center flex-col justify-center mt-[80px] w-full">
           {error?(<div className='flex items-center justify-center text-red-600 border border-red-600  w-[300px] p-2'><p>{error}</p></div>):null}
                   {success?(<div className="text-green-300 flex items-center justify-center"><p>{success}</p></div>):null}
           <h2 className="text-black p-3 text-3xl text-left">Sign In</h2>
               <form className="flex flex-col gap-4" onSubmit={login}>
                   <div className="w-full"><input type="email" placeholder="Email" value={email} className='p-2 w-[300px] rounded focus:outline-none text-black  border-[#FFFF] border-2 mb-[20px] shadow'  onChange={(e)=>setEmail(e.target.value)}/></div>
                   <div><input type="password" placeholder="Password" value={password} className='p-2 w-[300px] rounded focus:outline-none text-black shadow  border-[#FFFF] border-2'  onChange={(e)=>setPassword(e.target.value)}/></div>
                
                   <div><button className="bg-[#D1358F] p-2 w-[300px] rounded mt-[15px] text-white">Submit</button></div>
               </form>
              
           
               <div className='py-2'>New to Melodax ?<span className="text-[#D1358F]"> <Link href="signup">SignUp Now</Link></span> <span></span></div>
               <div><p>Go back <span className="text-[#D1358F]"><Link href="/">Home</Link></span></p></div>
           </div>

          

          

       </div>
       </>
  )
}

export default Login