import React,{useEffect,useState,useContext} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from "next/router"
import { collection,   onSnapshot,query } from "firebase/firestore";
import {firebaseapp} from "./components/firebase"
import {getFirestore} from "firebase/firestore"
import { Auth } from './components/Context';
import Link from "next/link"
import Navbar from './components/Navbar';

function Melodax() {
const [lists,setLists] = useState([])
const projectfirestore = getFirestore(firebaseapp)
const {user} = useContext(Auth)
const router = useRouter();
const getPosts = async () =>{

  const querySnapshot =query(collection(projectfirestore, "posts"));

  const unsubscribe = onSnapshot(querySnapshot, (querySnapshot) => {
    const cities = [];
    querySnapshot.forEach((doc) => {
        cities.push(doc.data());
    });
   setLists(cities)
  });
 
}

  useEffect(()=>{
    getPosts()

  })
  return (
    <>

<Head>
        <title>Meet Our Community </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Navbar/>
    <div className="md:h-[450px] bg-[#E23972] text-white py-4 flex justify-around flex-col md:flex-row items-center">
      <div className='md:ml-[100px] md:mt-[100px] mt-[80px] px-3'>
        <h1 className='text-6xl font-bold mb-[20px]'>Stay Curious and <br/>Ready To Learn</h1>
        <p>Discover stories, thinking, and expertise from writers on any topic.</p>
        <div className='mt-[50px]'>
          <button className='bg-white text-[#E23972] p-2 rounded-full w-[200px]'>{user ? <span onClick={()=>router.push("createpost")}>Create Post</span> : <span  onClick={()=>router.push('login')}>Start reading</span> }</button>
        </div>
      </div>
      <div className='p-4 mt-[60px]'>
      <Image src="/learn.png" width={500} height={250} alt="learn"></Image>
      </div>

     

    </div>

    <div className='mt-[100px] md:h-[100vh]  '>
<div className=' md:ml-[150px] grid grid-cols-1 md:grid-cols-4 gap-[30px]'>
    {lists.map((item)=>{
      return(
     <div  key={item.id} className=" w-[300px]"> <h1 className="text-2xl font-bold">{item?.title}</h1>
     <p className="text-sm w-[100px] ">{item?.post.substring(0,100)}....</p>
     <span className="cursor-pointer text-[#E23972]"><Link href={`/singlepost/${item?.id}`}>Read more</Link></span></div>
      )
    })}
    </div>
    </div>
    </>
  )
}

export default Melodax