import React,{useEffect,useState,useContext} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from "next/router"
import { collection,   getDocs } from "firebase/firestore";
import {firebaseapp} from "./components/firebase"
import {getFirestore} from "firebase/firestore"
import { Auth } from './components/Context';


function Melodax() {
const [lists,setLists] = useState([])
const projectfirestore = getFirestore(firebaseapp)
const {user} = useContext(Auth)
const router = useRouter();
const getPosts = async () =>{

  const querySnapshot = await getDocs(collection(projectfirestore, "posts"));
  querySnapshot.forEach((doc) => {
    const listItem = []
    listItem.push(doc.data())
    setLists(listItem)
    console.log(doc.data(),lists)
    // doc.data() is never undefined for query doc snapshots
   
  });
}

  useEffect(()=>{
    getPosts()

  })
  return (
    <>

<Head>
        <title>Meet Our Community </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    <div className="md:h-[450px] bg-[#E23972] text-white py-4 flex justify-around flex-col-reverse md:flex-row ">
      <div className='ml-[100px] mt-[100px]'>
        <h1 className='text-6xl font-bold mb-[20px]'>Stay Curious and <br/>Ready To Learn</h1>
        <p>Discover stories, thinking, and expertise from writers on any topic.</p>
        <div className='mt-[50px]'>
          <button className='bg-white text-[#E23972] p-2 rounded-full w-[200px]'>{user ? <span onClick={()=>router.push("createpost")}>Create Post</span> : <span  onClick={()=>router.push('login')}>Start reading</span> }</button>
        </div>
      </div>
      <div className='p-4'>
      <Image src="/learn.png" width={500} height={250} alt="learn"></Image>
      </div>

     

    </div>

    <div className='mt-[100px] h-[100vh] '>
<div className='flex flex-col ml-[150px]'>
    {lists.map((item)=>{
      return(
     <div  key={item.id} className="cursor-pointer"> <h1 className="text-3xl font-bold">{item?.title}</h1>
     <p>{item?.post}</p>
     <span className="cursor-pointer text-[#231A36]">Read more</span></div>
      )
    })}
    </div>
    </div>
    </>
  )
}

export default Melodax